name: Generate Docs

on:
  push:
    branches: [ master ]

jobs:
  dokka:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: gh-pages
    
    - name: Merge changes
      run: git merge origin/master
        
        
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: Generate docs
      run: gradlew dokka
      
    - name: Push changes
      uses: actions-go/push@v1
      with:
        author-email: github-actions@users.noreply.github.com
        author-name: GitHub Actions
        create-commit: true 
        commit-files: dokka/
        commit-message: Updated docs
        #token: # optional, default is ${{ github.token }}
      
